version: '3.9'

networks:
  app_network:
    name: offermanager_network
    driver: bridge

services:
  offermanager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app_network
    environment:
      DATABASE: db
    depends_on:
      - db

  db:
    image: postgres:13.11
    ports:
      - "5432:5432"
    networks:
      - app_network
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
